apiVersion: v2
name: prometheus-cardinality-exporter
description: A Helm chart for Prometheus Cardinality Exporter - monitors Prometheus instances to expose metrics about high-cardinality metrics
type: application
version: 0.3.0
appVersion: "latest"
keywords:
  - prometheus
  - monitoring
  - cardinality
  - metrics
  - observability
home: https://github.com/thought-machine/prometheus-cardinality-exporter
sources:
  - https://github.com/thought-machine/prometheus-cardinality-exporter
maintainers:
  - name: thought-machine
    url: https://github.com/thought-machine
icon: https://raw.githubusercontent.com/cncf/artwork/master/projects/prometheus/icon/color/prometheus-icon-color.svg
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/links: |
    - name: Documentation
      url: https://github.com/thought-machine/prometheus-cardinality-exporter#readme
    - name: Source
      url: https://github.com/thought-machine/prometheus-cardinality-exporter
  artifacthub.io/category: monitoring-logging
  artifacthub.io/changes: |
    - kind: added
      description: Initial Helm chart release
