{{- if and .Values.rbac.create (not .Values.rbac.clusterScope) -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "prometheus-cardinality-exporter.fullname" . }}
  labels:
    {{- include "prometheus-cardinality-exporter.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "prometheus-cardinality-exporter.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "prometheus-cardinality-exporter.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
