{{- if and .Values.auth.enabled (not .Values.auth.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "prometheus-cardinality-exporter.authSecretName" . }}
  labels:
    {{- include "prometheus-cardinality-exporter.labels" . | nindent 4 }}
type: Opaque
stringData:
  prometheus-api-auth-values.yaml: |
    {{- range $key, $value := .Values.auth.credentials }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
{{- end }}
